-- Seed remaining 29 RIASEC sector templates

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('r_build_fix', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"r_build_fix","riasec_type":"realistic","display_name":"Build & Fix","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is snapping blocks together fun for you right now?","activity_scene":{"activity_label":"Building a small tower","simple_picture_description":"Side-view of hands stacking three plain blocks. No faces.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('r_nature_outdoors', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"r_nature_outdoors","riasec_type":"realistic","display_name":"Nature Outdoors","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is walking on a leafy trail fun for you right now?","activity_scene":{"activity_label":"Trail exploring","simple_picture_description":"Simple path with trees and leaves. No people faces.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('r_sports_movement', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"r_sports_movement","riasec_type":"realistic","display_name":"Sports & Movement","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is climbing on playground bars fun for you right now?","activity_scene":{"activity_label":"Climbing and running","simple_picture_description":"Plain figure on monkey bars, side view. No facial detail.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('r_crafts_making', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"r_crafts_making","riasec_type":"realistic","display_name":"Crafts & Making","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is gluing paper shapes together fun for you right now?","activity_scene":{"activity_label":"Paper crafting","simple_picture_description":"Hands holding glue stick and colored paper. No faces.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('r_vehicles_machines', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"r_vehicles_machines","riasec_type":"realistic","display_name":"Vehicles & Machines","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is rolling toy wheels back and forth fun for you right now?","activity_scene":{"activity_label":"Toy wheels and trains","simple_picture_description":"Simple toy train on a track. Neutral colors.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('i_puzzles_logic', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"i_puzzles_logic","riasec_type":"investigative","display_name":"Puzzles & Logic","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is fitting puzzle pieces together fun for you right now?","activity_scene":{"activity_label":"Jigsaw puzzle","simple_picture_description":"Two puzzle pieces about to connect. Minimal background.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('i_nature_science', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"i_nature_science","riasec_type":"investigative","display_name":"Nature Science","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is looking at a bug with a magnifier fun for you right now?","activity_scene":{"activity_label":"Bug observing","simple_picture_description":"Magnifying glass over a leaf with a simple bug shape.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('i_numbers_patterns', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"i_numbers_patterns","riasec_type":"investigative","display_name":"Numbers & Patterns","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is lining up counting blocks in order fun for you right now?","activity_scene":{"activity_label":"Number patterns","simple_picture_description":"Colored blocks numbered 1-2-3 in a row.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('i_maps_exploring', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"i_maps_exploring","riasec_type":"investigative","display_name":"Maps & Exploring","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is tracing a path through a maze fun for you right now?","activity_scene":{"activity_label":"Maze path","simple_picture_description":"Simple top-down maze with one clear route.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('i_experiments_trying', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"i_experiments_trying","riasec_type":"investigative","display_name":"Experiments & Trying","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is mixing two safe liquids in a cup fun for you right now?","activity_scene":{"activity_label":"Mix and try","simple_picture_description":"Two beakers pouring into one cup. No faces.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('a_drawing_color', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"a_drawing_color","riasec_type":"artistic","display_name":"Drawing & Color","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is filling shapes with bright colors fun for you right now?","activity_scene":{"activity_label":"Coloring shapes","simple_picture_description":"Crayons next to an outlined star and circle.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('a_music_rhythm', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"a_music_rhythm","riasec_type":"artistic","display_name":"Music & Rhythm","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is tapping a steady beat on a drum fun for you right now?","activity_scene":{"activity_label":"Rhythm tapping","simple_picture_description":"Simple hand tapping a plain drum. No face.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('a_story_imagine', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"a_story_imagine","riasec_type":"artistic","display_name":"Story & Imagine","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is making up a silly story out loud fun for you right now?","activity_scene":{"activity_label":"Story imagining","simple_picture_description":"Open book with a star and moon icons floating above.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('a_build_design', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"a_build_design","riasec_type":"artistic","display_name":"Build & Design","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is arranging shapes into a new pattern fun for you right now?","activity_scene":{"activity_label":"Shape design","simple_picture_description":"Triangles and squares forming a new layout.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('a_performance_show', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"a_performance_show","riasec_type":"artistic","display_name":"Performance & Show","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is acting out a short scene with toys fun for you right now?","activity_scene":{"activity_label":"Toy performance","simple_picture_description":"Two toy figures on a small stage. No faces.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('s_helping_caring', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"s_helping_caring","riasec_type":"social","display_name":"Helping & Caring","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is gently caring for a toy doll fun for you right now?","activity_scene":{"activity_label":"Caring play","simple_picture_description":"Hands tucking a blanket around a plain toy figure.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('s_teaching_showing', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"s_teaching_showing","riasec_type":"social","display_name":"Teaching & Showing","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is showing a friend how a toy works fun for you right now?","activity_scene":{"activity_label":"Showing a toy","simple_picture_description":"One hand pointing at toy gears while another watches.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('s_team_play', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"s_team_play","riasec_type":"social","display_name":"Team Play","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is passing a ball back and forth with someone fun for you right now?","activity_scene":{"activity_label":"Cooperative ball play","simple_picture_description":"Two plain figures passing a ball. No facial detail.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('s_community_events', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"s_community_events","riasec_type":"social","display_name":"Community Events","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is walking through a busy fair with stalls fun for you right now?","activity_scene":{"activity_label":"Fair exploring","simple_picture_description":"Simple tents and banner flags. No crowd faces.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('s_friend_connections', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"s_friend_connections","riasec_type":"social","display_name":"Friend Connections","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is sharing a snack with a friend fun for you right now?","activity_scene":{"activity_label":"Friend sharing","simple_picture_description":"Two plain cups and a small snack plate.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('e_leading_groups', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"e_leading_groups","riasec_type":"enterprising","display_name":"Leading Groups","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is picking the next group game fun for you right now?","activity_scene":{"activity_label":"Leading play","simple_picture_description":"Plain figure pointing at three game cards on the ground.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('e_selling_trading', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"e_selling_trading","riasec_type":"enterprising","display_name":"Trading & Swapping","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is swapping trading cards with a friend fun for you right now?","activity_scene":{"activity_label":"Card swapping","simple_picture_description":"Two hands exchanging plain cards.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('e_planning_events', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"e_planning_events","riasec_type":"enterprising","display_name":"Planning Events","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is planning a pretend picnic fun for you right now?","activity_scene":{"activity_label":"Picnic planning","simple_picture_description":"Checklist next to a blanket and basket icon.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('e_persuading_sharing', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"e_persuading_sharing","riasec_type":"enterprising","display_name":"Sharing Ideas","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is telling someone about a fun idea fun for you right now?","activity_scene":{"activity_label":"Idea sharing","simple_picture_description":"Speech bubble with a lightbulb icon. No face.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('e_starting_projects', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"e_starting_projects","riasec_type":"enterprising","display_name":"Starting Projects","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is starting a new craft project fun for you right now?","activity_scene":{"activity_label":"New project start","simple_picture_description":"Blank paper, scissors, and tape laid out neatly.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('c_sorting_organizing', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"c_sorting_organizing","riasec_type":"conventional","display_name":"Sorting & Organizing","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is sorting buttons by color fun for you right now?","activity_scene":{"activity_label":"Color sorting","simple_picture_description":"Buttons grouped into three color piles.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('c_schedules_routines', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"c_schedules_routines","riasec_type":"conventional","display_name":"Schedules & Routines","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is following a picture schedule fun for you right now?","activity_scene":{"activity_label":"Picture schedule","simple_picture_description":"Three picture cards in a row with arrows.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('c_lists_checklists', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"c_lists_checklists","riasec_type":"conventional","display_name":"Lists & Checklists","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is checking off a simple to-do list fun for you right now?","activity_scene":{"activity_label":"Checklist play","simple_picture_description":"Clipboard with three checkboxes, two checked.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('c_collecting_sets', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"c_collecting_sets","riasec_type":"conventional","display_name":"Collecting Sets","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is lining up a complete sticker set fun for you right now?","activity_scene":{"activity_label":"Set collecting","simple_picture_description":"Sticker sheet with one empty spot highlighted.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;

insert into public.riasec_sector_templates (sector_id, template_version, template_json, golden_rule_ack)
values ('c_patterns_order', '2026-08-24', '{"template_version":"2026-08-24","sector_id":"c_patterns_order","riasec_type":"conventional","display_name":"Patterns & Order","framing_rules":{"golden_rule":"Measure present-moment enjoyment only. Never reference future jobs, careers, salaries, or adult work roles.","prompt_tone":"playful_now","forbidden_terms":["career","job","employ","salary","when you grow up","become a","profession","industry"],"required_framing":"Ask whether the child is enjoying this activity right now."},"visual_guidelines":{"style":"simple_stylized_drawing","show_gender_features":false,"show_complex_facial_expressions":false,"focus":"concrete_activity_only","avoid_visual_clutter":true},"sample_generated_task":{"present_moment_prompt":"Is making a repeating color pattern fun for you right now?","activity_scene":{"activity_label":"Pattern making","simple_picture_description":"Red-blue-red-blue bead sequence on a string.","optional_video_loop_description":"Silent 3-second activity loop with no background music."},"response_modality":"picture","enjoyment_scale":{"type":"present_moment_likert_visual","min_label":"Not fun right now","max_label":"Really fun right now"}},"play_concept_sources":["pediatric_iconographic_inventories","elementary_hobby_drawings_age_8_to_13"]}'::jsonb, true)
on conflict (sector_id, template_version) do update set template_json = excluded.template_json, active = true;
